### ISSUE TITLE
xgterm

### ISSUE THREAD

**Issue by Mohammad-Mardini** [iraf-community/iraf#90] opened 2019-08-22 09:19 UTC
Hi guys.

Thank you for keeping IRAF alive!!!!
I'm trying to install IRAF on my fresh MacBook (High Sierra 10.13.6). I followed the instructions provided by you, and everything went smoothly. Unfortunately, when I tried to call IRAF by typing iraf I got an error saying that I don't have xgterm, while calling it by cl works fine.

Could you please help me with this issue?

Thanks in advance.

**Comment by olebole** [comment] 2019-08-22 12:34
xgterm is part of the "x11iraf" package that is distributed independently in https://github.com/iraf-community/x11iraf. Alternatively, you can use the normal `xterm`, or [pyraf](https://pypi.org/project/pyraf/).
Since this is not a bug, I am going to close this.

**Closed by olebole** 2019-08-22 12:34 UTC
