### ISSUE TITLE
ERROR: Cannot open image

### ISSUE THREAD

**Issue by AminJafraov** [iraf-community/iraf#123] opened 2020-10-16 20:20 UTC
I am accessing my university's server to use IRAF. I have some .fits images uploaded to the server and I am trying to open them but it always says ERROR: Cannot open image. I think I created a new login file, which created the issues. How can I fix this?

**Comment by olebole** [comment] 2020-10-17 12:15
Did you get in contact with your university (who maintains the IRAF version there) to see whether it may be a local problem?

**Comment by olebole** [comment] 2020-10-22 15:30
From your text I would suspect this is either a local installation problem or a problem with the files themself. Therefore I am going  to close the issue for the moment. Please re-open with a detailed, reproducible description if it seems to be a bug in the IRAF community software.

**Closed by olebole** 2020-10-22 15:30 UTC
